# Generated by Django 5.2.3 on 2025-06-28 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('idaula', models.AutoField(db_column='idAula', primary_key=True, serialize=False)),
                ('capacidad', models.CharField(max_length=20)),
                ('aire', models.IntegerField()),
                ('videobeam', models.IntegerField()),
                ('pizarra', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.AutoField(db_column='idCarrera', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('numero_semestre', models.IntegerField()),
                ('modalidad', models.CharField(max_length=15)),
                ('mencion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.AutoField(db_column='idEstudiante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('telefeno', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('fecha_ing', models.DateField()),
            ],
            options={
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idmateria', models.AutoField(db_column='idMateria', primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=20)),
                ('unidades_creditos', models.IntegerField()),
                ('modalidad', models.CharField(max_length=20)),
                ('idcarrera', models.IntegerField(db_column='idCarrera')),
            ],
            options={
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('idprofesor', models.AutoField(db_column='idProfesor', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profesores/')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.CreateModel(
            name='CarreraEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcarrera', models.ForeignKey(db_column='idCarrera', on_delete=django.db.models.deletion.DO_NOTHING, to='app.carrera')),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estudiante')),
            ],
            options={
                'db_table': 'carreraestudiante',
            },
        ),
        migrations.CreateModel(
            name='HorarioEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('horario_inicio', models.CharField(max_length=15)),
                ('horario_fin', models.CharField(max_length=15)),
                ('idaula', models.ForeignKey(db_column='idAula', on_delete=django.db.models.deletion.DO_NOTHING, to='app.aula')),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estudiante')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
            ],
            options={
                'db_table': 'horarioestudiante',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idestudiante', models.ForeignKey(db_column='idEstudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='app.estudiante')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
            ],
            options={
                'db_table': 'nota',
            },
        ),
        migrations.CreateModel(
            name='MateriaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
                ('idprofesor', models.ForeignKey(db_column='idProfesor', on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesor')),
            ],
            options={
                'db_table': 'materiaprofesor',
            },
        ),
        migrations.CreateModel(
            name='HorarioProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=15)),
                ('horario_inicio', models.CharField(max_length=15)),
                ('horario_fin', models.CharField(max_length=15)),
                ('idaula', models.ForeignKey(db_column='idAula', on_delete=django.db.models.deletion.DO_NOTHING, to='app.aula')),
                ('idmateria', models.ForeignKey(db_column='idMateria', on_delete=django.db.models.deletion.DO_NOTHING, to='app.materia')),
                ('idprofesor', models.ForeignKey(db_column='idProfesor', on_delete=django.db.models.deletion.DO_NOTHING, to='app.profesor')),
            ],
            options={
                'db_table': 'horarioprofesor',
            },
        ),
    ]
